### ISSUE TITLE
[Enhancement] Tint2 Executor like applet

### ISSUE THREAD

**Issue by purpleleaf** [plainDE/plainPanel#29]
The only thing i'm missing on plainPanel is an applet that allow the execution of other programs/scripts, allowing to change the icon or text accordling, like tint2 executor or xfce4 panel genmon do, interacting also with mouse click and mouse wheel.
I know  future development of plaiPanel is going to provide all the stuff needed for a 'normal' usage, but there are cases where someone runs minimal desktop without for example network manager (and wants implement a DIY applet to manage dhcp and iwd or wpa_supplicant using jgmenu fo example, as i do) or  want check updates for arch without using 100MB RAM only to show an icon to check updates or want monitor the output of other software.

**Comment by thm-unix** [comment]
Hello! There is an applet called 'Launcher'. It allows you to run any *.desktop file from /usr/share/applications or ~/.local/share/applications. 

1. Create your own *.desktop file
Sample: /usr/share/applications/my-applet.desktop
```
[Desktop Entry]
Name=MyApplet
Type=Application
Exec=/path/to/script
```
// if you don't want it to show up in App menu, then add ```NoDisplay=true```
2. Open plainControlCenter (a.k.a. Settings)
3. Go to Panels pane
4. Select panel where you want to put your launcher
5. Select 'launcher' from left list and click '>>' button to add it 
6. Type my-applet.desktop and click OK
7. Adjust your launcher position in right list by clicking arrows up and down
8. Click 'Save selected panel configuration'

In next release we plan to extend 'Launcher' applet capability (running script or file without creating *.desktop file). CLI output applet is also planned.

About your previous issue (battery icon theme). I fixed it. Fix will be available in 0.5.2 (expect it in a week)

**Comment by purpleleaf** [comment]
Hi thm-unix
thanks for fixing previous issue, i'll be looking forward to next release :)

Thanks for your suggestion, i already use some custom launchers and I can't wait to new features implementation.
About CLI output applet i hope i it will able to change the applet icon :) In my dream the perfect applet is a mix of the best features of xfce4 genmon applet ant tint2 executors (xml settings and bar output from genmon, mouse click and wheel actions from tint2)

**Comment by thm-unix** [comment]
Hello! plainDE 0.5.2 is out. Here are release notes: [https://github.com/plainDE/plainPanel/releases/tag/0.5.2](https://github.com/plainDE/plainPanel/releases/tag/0.5.2). I will close issue about battery icons & will leave this open not to forget about CLI output applet. Thank you for your feedback. 

As for the update, I'd recommend you to run this command again in order to download & install plainDE 0.5.2:
```sh -c "$(curl -fsSL plainde.github.io/install)"```

Hope you will enjoy using new version. Thank you for your feedback, it's very important for us.

**Comment by thm-unix** [comment]
Hello again! plainDE 0.6 is out. Here are release notes: [https://github.com/plainDE/plainPanel/releases/tag/0.6](https://github.com/plainDE/plainPanel/releases/tag/0.6). Among other features, CLI Output applet is out now! plainControlCenter doesn't support it fully yet, so guide on how to configure it can be found here: [https://plainde.github.io/docs.github.io/clioutputapplet.html](https://plainde.github.io/docs.github.io/clioutputapplet.html). 

Run this command in order to update to plainDE 0.6:
`sh -c "$(curl -fsSL plainde.github.io/install)"`

Thank you for suggestion a feature. Hope you will enjoy using the latest version of plainDE. Feel free to leave feedback if something's broken or you have another idea for new feature.

**Comment by purpleleaf** [comment]
Hi thm-unix :)
Tested right now the new CLI Output applet.
Great work!!
I have just made a tint2 executor to show a a wired/wireless/no connection icon according to network status; i will try to port it to CLI output applet.

I just propose a little change to the help page in https://plainde.github.io/docs.github.io/clioutputapplet.html.
Where it says "Add clioutput:[name] in applets", it seems that the applet file name should be surrounded by square bracket; doing so plainPanel crashes at startup. It is also not clear if the file name must have the json extension or not. 
I suggest to add an example to make it more clear.

Many thanks!

**Comment by thm-unix** [comment]
Hello! Thank you for your feedback, I'll make these changes to the documentation.

**Comment by thm-unix** [comment]
Hello again! plainDE 0.6.1 is out. Here are release notes: [https://github.com/plainDE/plainPanel/releases/tag/0.6.1](https://github.com/plainDE/plainPanel/releases/tag/0.6.1). Key features were extended CLI Output applet functionality and bugfix. Please consider updating and edit your CLI Output applet config. Latest version features `elseCondition` option that can be useful when command failed to run or gives unexpected output. Also plainControlCenter now fully supports CLI Output applet.

Run this command in order to update to plainDE 0.6.1:
```sh -c "$(curl -fsSL plainde.github.io/install)"```

Best regards,
thm-unix
